[package]
name = "shrimply-timeline-value"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true, features = ["serde"] }
num-traits.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-math-color = { path = "../../math/color" }
shrimply-render-core = { path = "../../render-core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-math-geometry = { path = "../../math/geometry" }
shrimply-transform-3d = { path = "../../3d/transform-3d" }
unicode-segmentation.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
