[package]
name = "shrimply_cuda_preview"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "c58c30f2af8bfab0462f6abfc546cbfcc8ad57a0" }
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "c58c30f2af8bfab0462f6abfc546cbfcc8ad57a0" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "c58c30f2af8bfab0462f6abfc546cbfcc8ad57a0" }
glam = "0.33"
shrimply-render-core = { path = "../../render-core" }
shrimply-math-color = { path = "../../math/color", features = ["cuda"] }
