[package]
name = "shrimply-scene-3d-modifiers"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
glam = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
shrimply-asset = { path = "../../asset" }
shrimply-core = { path = "../../core" }
shrimply-scene-3d = { path = "../scene-3d" }
shrimply-shape-3d = { path = "../shape-3d" }
shrimply-text-3d = { path = "../text-3d" }
uuid = { workspace = true, features = ["v4", "serde"] }
