[package]
name = "shrimply-paint-model"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
shrimply-asset = { path = "../../asset" }
shrimply-paint-interpolation = { path = "../paint-interpolation" }
shrimply-timeline-value = { path = "../../timeline/timeline-value" }
shrimply-math-color = { path = "../../math/color" }
shrimply-math-geometry = { path = "../../math/geometry" }
uuid = { workspace = true, features = ["v4", "serde"] }
