[package]
name = "shrimply_cuda_modifiers_geometry"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
cuda-core = { path = "../../../external/cuda-oxide/crates/cuda-core" }
cuda-device = { path = "../../../external/cuda-oxide/crates/cuda-device" }
cuda-host = { path = "../../../external/cuda-oxide/crates/cuda-host" }
shrimply-render-core = { path = "../../render-core" }
